### ISSUE TITLE
Ubuntu 24.04 LTS Compatibility Issues

### ISSUE THREAD

**Issue by johnmart19** [DumprX/DumprX#31]
## To install DumperX dependencies was mandatory to install python3-venv
`sudo apt install python3-venv`

## Issue Description
Following error occures when trying to dump [HyperOS 1.0.2.0 Global Mi for Xiaomi Poco F3 (Alioth)](https://cdnorg.d.miui.com/OS1.0.2.0.TKHMIXM/miui_ALIOTHGlobal_OS1.0.2.0.TKHMIXM_b69e6a5400_13.0.zip)
On Ubuntu 22.04 LTS were no issues, error occures only with latest.
### Extracting system failed:
```
Extracting system partition...
Extraction Failed my 7z
Couldn't extract system partition by 7z. Using fsck.erofs.
<E> erofs: cannot find valid erofs superblock
<E> erofs: failed to read superblock
Couldn't extract system partition by fsck.erofs. Using mount loop
mount: /home/johnmart19/miui/out/system: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
cp: cannot stat 'system/*': No such file or directory
umount: system: not mounted.
cp: cannot stat 'system_/*': No such file or directory
chown: cannot access 'system/*': No such file or directory
chmod: cannot access 'system/*': No such file or directory
Couldn't extract system partition. It might use an unsupported filesystem.
For EROFS: make sure you're using Linux 5.4+ kernel.
For F2FS: make sure you're using Linux 5.15+ kernel.
Extracting system_ext partition...
```

### TWRP DT Generator error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/johnmart19/miui/.venv/lib/python3.12/site-packages/twrpdtgen/__main__.py", line 8, in <module>
    from twrpdtgen.main import main
  File "/home/johnmart19/miui/.venv/lib/python3.12/site-packages/twrpdtgen/main.py", line 11, in <module>
    from twrpdtgen.device_tree import DeviceTree
  File "/home/johnmart19/miui/.venv/lib/python3.12/site-packages/twrpdtgen/device_tree.py", line 12, in <module>
    from sebaubuntu_libs.libandroid.device_info import DeviceArch, DeviceInfo
  File "/home/johnmart19/miui/.venv/lib/python3.12/site-packages/sebaubuntu_libs/libandroid/device_info.py", line 7, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
```

### Redownloaded fully to review that it's not an error with download
```
[#e5a7e9 3.7GiB/3.7GiB(99%) CN:1 DL:78MiB]
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e5a7e9|OK  |    87MiB/s|/home/johnmart19/miui/input/miui_ALIOTHGlobal_OS1.0.2.0.TKHMIXM_b69e6a5400_13.0.zip

Status Legend:
(OK):download completed.

Working with miui_ALIOTHGlobal_OS1.0.2.0.TKHMIXM_b69e6a5400_13.0.zip

Extracting firmware on: /home/johnmart19/miui/out
AB OTA Payload Detected
```
### Installed all python3 packages
`sudo apt install python3-full`

#### Issue not resolved.

**Comment by Sushrut1101** [comment]
Fixed
