### ISSUE TITLE
Failing to install aospdtgen

### ISSUE THREAD

**Issue by wshamroukh** [DumprX/DumprX#32]
I am getting this error while trying to install `aospdtgen`

```
Collecting git+https://github.com/sebaubuntu-python/aospdtgen
  Cloning https://github.com/sebaubuntu-python/aospdtgen to /tmp/pip-cz_jnklq-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-cz_jnklq-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-cz_jnklq-build/
Setup Failed!
```
And looking under the tmp folder cloned, indeed there is no setup.py

```
ls -al /tmp/pip-cz_jnklq-build/
total 72
drwxr-xr-x  6 root root  4096 May 12 20:18 .
drwxrwxrwt 20 root root  4096 May 12 20:23 ..
drwxr-xr-x  5 root root  4096 May 12 20:18 aospdtgen
drwxr-xr-x  8 root root  4096 May 12 20:18 .git
drwxr-xr-x  2 root root  4096 May 12 20:18 .github
-rw-r--r--  1 root root  2885 May 12 20:18 .gitignore
-rw-r--r--  1 root root   185 May 12 20:18 pip-delete-this-directory.txt
drwxr-xr-x  2 root root  4096 May 12 20:18 pip-egg-info
-rw-r--r--  1 root root 30494 May 12 20:18 poetry.lock
-rw-r--r--  1 root root   569 May 12 20:18 pyproject.toml
-rw-r--r--  1 root root  1500 May 12 20:18 README.md

```

Is there any way to overcome this?

**Comment by dkpost3** [comment]
restart setup in sudo mode
